engines:
    phpcodesniffer:
        enabled: true
    phpmd:
        enabled: true
    duplication:
        enabled: true
        config:
          languages:
          - php

ratings:
    paths:
        - "lib/*.php"

exclude_paths:
- "modules/*"
- "tests/*"
- "third_party/*"
- "docs/*"
- "language/*"
- "website/*"
