<?php
/**
 * AUTOGENERATED ONLY IF ABSENT
 * Edit this file to match your needs
 * To reset from defaults, run `composer horde:reconfigure --force --mode=proxy`
 */
$deployment_webroot = '/';
$deployment_fileroot = '/opt/homebrew/var/www/cypht/web';
$app_fileroot = '/opt/homebrew/var/www/cypht/web/horde';
$app_webroot = '/horde';
