name: Gen Latest

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  workflow_dispatch: # on button click
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Composer (php-actions)
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"

      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v3
        with:
          configuration: tests/phpunit/phpunit.xml
          php_version: "7.4"


