name: Gen Latest

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  workflow_dispatch: # on button click
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
         host port: 3306
         container port: 3306
         mysql database: 'cypht_test'
         mysql root password: 'cypht_test'
         mysql user: 'cypht_test'
         mysql password: 'cypht_test'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Composer (php-actions)
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"

      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v3
        with:
          configuration: tests/phpunit/phpunit.xml
          php_version: "7.4"
          version: 9


